-- Seed the first Turtle Terraria / auto-build research objects and demonstrate exhaustive tagging.
-- These are later operational mappings, not revisions to the original dissertation code layer.

PRAGMA foreign_keys = ON;

-- Repository artifacts created in the first Terraria architecture cycle.
INSERT OR IGNORE INTO research_objects
(id,object_type,title,summary,repo_path,source_uri,created_at,privacy_class,evidence_class,provenance_json) VALUES
('repo_file:research/TURTLE_TERRARIA.md','repository_artifact','Turtle Terraria research design','Defines the umbrella research environment, the first two habitats, provenance boundaries, open CTC-domain discovery, and exhaustive tagging doctrine.','research/TURTLE_TERRARIA.md','https://github.com/turtleblockai/platform/blob/main/research/TURTLE_TERRARIA.md','2026-09-08T20:20:00Z','public','human_authored','{"authorship":"human-directed co-active development","source_layer":"operational_turtle"}'),
('repo_file:migrations/0007_turtle_terraria_and_exhaustive_tagging.sql','repository_artifact','Turtle Terraria + exhaustive tagging schema','Adds the universal research-object registry, Terraria habitats and traces, auto-build research records, ontology/CTC/emergent tags, and an explicit pool for observations not captured by the seven established CTC domains.','migrations/0007_turtle_terraria_and_exhaustive_tagging.sql','https://github.com/turtleblockai/platform/blob/main/migrations/0007_turtle_terraria_and_exhaustive_tagging.sql','2026-09-08T20:20:00Z','public','human_authored','{"authorship":"human-directed co-active development","schema_version":"terraria-0.1"}'),
('build_log_entry:2026-09-08-turtle-terraria-tagging','build_log_entry','Turtle Terraria + exhaustive research tagging architecture','Public newest-first record of the Turtle Terraria naming, initial habitats, SQL architecture, and open-domain design.','src/buildLog.ts','https://github.com/turtleblockai/platform/blob/main/src/buildLog.ts','2026-09-08T20:20:00Z','public','human_authored','{"public_build_log":true}');

-- First auto-build events. These make the deliberative process queryable instead of leaving it
-- only in prose. The earlier run itself is seeded by migration 0007.
INSERT OR IGNORE INTO autobuild_events
(id,run_id,sequence_number,created_at,event_type,actor_type,title,content,source_url,external_date,payload_json,provenance_json) VALUES
('abe-20260908-01','autobuild-2026-09-08',1,'2026-09-08T18:40:00Z','source_signal','external_source','OpenAI: research agents remain human-supervised','Longer-horizon agentic research increases capability while still depending on human steering, intervention, judgment, and evaluation.','https://openai.com/index/research-acceleration-view-inside-openai/','2026-09-06','{"provider":"OpenAI"}','{"source_type":"primary_external"}'),
('abe-20260908-02','autobuild-2026-09-08',2,'2026-09-08T18:41:00Z','source_signal','external_source','NVIDIA: correction and audit trail','Memory architecture separates source evidence, derived knowledge, corrections, and audit events instead of silently rewriting history.','https://developer.nvidia.com/blog/building-a-memory-driven-agent-with-nvidia-nemoclaw/','2026-09-04','{"provider":"NVIDIA"}','{"source_type":"primary_external"}'),
('abe-20260908-03','autobuild-2026-09-08',3,'2026-09-08T18:42:00Z','source_signal','external_source','Minecraft Education: persistent cross-tenant worlds','Dedicated-server cross-tenant multiplayer strengthens the later case for shared multi-user TurtleBlock worlds but does not justify pulling that work into v0.1.','https://edusupport.minecraft.net/hc/en-us/articles/360047556451-Minecraft-Education-Change-Log','2026-09-01','{"provider":"Minecraft Education"}','{"source_type":"primary_external"}'),
('abe-20260908-04','autobuild-2026-09-08',4,'2026-09-08T18:43:00Z','source_signal','external_source','MIT Media Lab: machines adapt to human ambiguity','The Put That There lineage emphasizes natural human language, visible feedback, ambiguity resolution, and easy correction rather than forcing people into machine syntax.','https://www.media.mit.edu/posts/in-1979-researchers-here-said-put-that-there-openai-just-called-it-the-future/','2026-09-04','{"provider":"MIT Media Lab"}','{"source_type":"primary_external"}'),
('abe-20260908-05','autobuild-2026-09-08',5,'2026-09-08T18:50:00Z','ontology_mapping','automation','Ontology deliberation','The strongest immediate overlap is a visible human-machine correction loop rather than greater autonomy.','',NULL,'{"ctc_domains":["personal_inquiry","technology_as_tool_to_think_with","formative_demonstration_of_learning","reflection_as_learning","social_and_cultural_critique","sharing_and_collaborating"],"concepts":["co_active_emergence","provenance_aware_retrieval"]}','{"later_operational_mapping":true}'),
('abe-20260908-06','autobuild-2026-09-08',6,'2026-09-08T18:55:00Z','candidate','automation','Candidate: generalized persistent personal memory','Useful but deferred because identity, privacy, deletion, and preference-governance questions exceed the current v0.1 scope.',NULL,NULL,'{"decision":"defer","roadmap":"v0.3"}','{"deliberation":true}'),
('abe-20260908-07','autobuild-2026-09-08',7,'2026-09-08T18:56:00Z','rejection','automation','Rejected for now: more autonomous learner-facing agents','Greater autonomy does not solve the current research problem and may conceal interpretation or reduce learner agency.',NULL,NULL,'{"decision":"reject_for_now"}','{"deliberation":true}'),
('abe-20260908-08','autobuild-2026-09-08',8,'2026-09-08T18:58:00Z','selection','automation','Selected: Co-Active Trace','Preserve learner intent, Turtle interpretation, human steering, ontology mappings, and resulting WorldSpec revision as distinguishable provenance states.',NULL,NULL,'{"selected":true,"target":"v0.1.x"}','{"deliberation":true}'),
('abe-20260908-09','autobuild-2026-09-08',9,'2026-09-08T19:30:00Z','implementation','automation','Newest-first public Build Log architecture','Added a small Worker-side Build Log layer so daily entries can be prepended safely without editing the large SPA by hand.',NULL,NULL,'{"files":["src/buildLog.ts","src/entry.ts","wrangler.jsonc"]}','{"repository_change":true}'),
('abe-20260908-10','autobuild-2026-09-08',10,'2026-09-08T20:20:00Z','human_override','human','Turtle Terraria conceptual expansion','Human research direction expands Turtle Lab into Turtle Terraria, establishes two initial habitats, requires exhaustive tagging, and explicitly preserves room for future CTC domains that evidence may reveal.',NULL,NULL,'{"habitats":["human_turtle","recursive_turtle"],"open_ctc_domains":true,"exhaustive_tagging":true}','{"human_direction":true}');

-- Register direct repository changes associated with this conceptual expansion.
INSERT OR IGNORE INTO autobuild_repo_changes
(id,run_id,created_at,repo_path,change_type,commit_sha,summary,provenance_json) VALUES
('abc-20260908-terraria-sql','autobuild-2026-09-08','2026-09-08T20:20:00Z','migrations/0007_turtle_terraria_and_exhaustive_tagging.sql','create','0fbac62789e418d1fcfed2584528f8396775b552','Created first-class Terraria, universal research object, open CTC-domain, and auto-build capture schema.','{"cycle":"terraria_expansion"}'),
('abc-20260908-terraria-doc','autobuild-2026-09-08','2026-09-08T20:21:00Z','research/TURTLE_TERRARIA.md','create','aad3b43f8b079d464e6f6e36396be6fa89282ee6','Documented habitats, provenance boundary, open-domain method, and exhaustive tagging doctrine.','{"cycle":"terraria_expansion"}'),
('abc-20260908-terraria-www','autobuild-2026-09-08','2026-09-08T20:22:00Z','src/entry.ts','update','20540187522a5646ee36014df2816fe37d1cf3cf','Rebranded WWW Turtle Lab language as Turtle Terraria and exposed the Human + Turtle and Recursive Turtle habitats.','{"cycle":"terraria_expansion","legacy_path":"/lab/"}'),
('abc-20260908-terraria-log','autobuild-2026-09-08','2026-09-08T20:23:00Z','src/buildLog.ts','update','9aeaac9196b1b6990ac1888b636413e9d73a36db','Prepended the Turtle Terraria architecture to the public newest-first Build Log.','{"cycle":"terraria_expansion"}');

-- Repository design artifact: broad CTC coverage. These are operational mappings, not claims
-- that a learner demonstrated the domain.
INSERT OR IGNORE INTO research_object_ctc_tags
(id,object_id,domain_id,tag_role,confidence,tagging_method,actor_type,rationale,status,created_at,provenance_json) VALUES
('tag-terraria-ctc01','repo_file:research/TURTLE_TERRARIA.md','ctc-domain-01','supports',1.0,'human','researcher','Human + Turtle habitat preserves human-originated inquiry as primary evidence.','accepted','2026-09-08T20:25:00Z','{"scope":"research_design_not_learner_assessment"}'),
('tag-terraria-ctc02','repo_file:research/TURTLE_TERRARIA.md','ctc-domain-02','supports',1.0,'human','researcher','Terraria traces preserve questions and unresolved problems across iterations.','accepted','2026-09-08T20:25:00Z','{"scope":"research_design_not_learner_assessment"}'),
('tag-terraria-ctc03','repo_file:research/TURTLE_TERRARIA.md','ctc-domain-03','primary',1.0,'human','researcher','The environment explicitly studies computers as participants/objects to think with rather than push-button terminals.','accepted','2026-09-08T20:25:00Z','{"scope":"research_design_not_learner_assessment"}'),
('tag-terraria-ctc04','repo_file:research/TURTLE_TERRARIA.md','ctc-domain-04','supports',0.95,'human','researcher','Intermediate changes, corrections, traces, and artifacts are captured rather than only final outputs.','accepted','2026-09-08T20:25:00Z','{"scope":"research_design_not_learner_assessment"}'),
('tag-terraria-ctc05','repo_file:research/TURTLE_TERRARIA.md','ctc-domain-05','primary',1.0,'human','researcher','Reflection and revision are first-class Terraria events and observations.','accepted','2026-09-08T20:25:00Z','{"scope":"research_design_not_learner_assessment"}'),
('tag-terraria-ctc06','repo_file:research/TURTLE_TERRARIA.md','ctc-domain-06','primary',1.0,'human','researcher','Provenance-preserving critique allows assumptions, values, positionality, and machine-imposed categories to be examined.','accepted','2026-09-08T20:25:00Z','{"scope":"research_design_not_learner_assessment"}'),
('tag-terraria-ctc07','repo_file:research/TURTLE_TERRARIA.md','ctc-domain-07','primary',1.0,'human','researcher','Cohabitation and collaboration among human and computational participants is the central environment design.','accepted','2026-09-08T20:25:00Z','{"scope":"research_design_not_learner_assessment"}');

INSERT OR IGNORE INTO research_object_ontology_tags
(id,object_id,concept_id,tag_role,confidence,tagging_method,actor_type,rationale,status,created_at,provenance_json) VALUES
('tag-terraria-concept-self','repo_file:research/TURTLE_TERRARIA.md','concept-turtle-terraria','primary',1.0,'human','researcher','The document defines the Turtle Terraria environment.','accepted','2026-09-08T20:25:00Z','{"later_operational_mapping":true}'),
('tag-terraria-concept-coactive','repo_file:research/TURTLE_TERRARIA.md','concept-coactive-emergence','operationalizes',1.0,'human','researcher','Human + Turtle habitat makes purposeful human-machine interaction observable as a trace.','accepted','2026-09-08T20:25:00Z','{"later_operational_mapping":true}'),
('tag-terraria-concept-recursion','repo_file:research/TURTLE_TERRARIA.md','concept-recursive-learning-loop','extends',1.0,'human','researcher','Both habitats preserve iterative interpretation, observation, reflection, and revision.','accepted','2026-09-08T20:25:00Z','{"later_operational_mapping":true}'),
('tag-terraria-concept-provenance','repo_file:research/TURTLE_TERRARIA.md','concept-provenance-aware-retrieval','extends',1.0,'human','researcher','Cohabitation is permitted only while human, machine, synthetic, world, and source provenance remain distinguishable.','accepted','2026-09-08T20:25:00Z','{"later_operational_mapping":true}'),
('tag-terraria-concept-pce','repo_file:research/TURTLE_TERRARIA.md','concept-persistent-computing-environment','extends',0.95,'human','researcher','Each Terrarium is defined as a bounded persistent environment carrying history, actors, relationships, and traces forward.','accepted','2026-09-08T20:25:00Z','{"later_operational_mapping":true}'),
('tag-terraria-concept-synth','repo_file:research/TURTLE_TERRARIA.md','concept-synthetic-recursive-dialogue','primary',1.0,'human','researcher','The Recursive Turtle habitat explicitly defines bounded machine-to-machine self-play.','accepted','2026-09-08T20:25:00Z','{"later_operational_mapping":true,"human_evidence":false}');

-- Tag the auto-build run itself so system development can later be mined through the same ontology.
INSERT OR IGNORE INTO research_object_ontology_tags
(id,object_id,concept_id,tag_role,confidence,tagging_method,actor_type,rationale,status,created_at,provenance_json) VALUES
('tag-autobuild-coactive','autobuild_run:autobuild-2026-09-08','concept-coactive-emergence','tests',0.95,'mixed','researcher','Machine hunt/deliberation and human redirection visibly alter the resulting repository work.','accepted','2026-09-08T20:26:00Z','{"scope":"system_research","human_learning_evidence":false}'),
('tag-autobuild-recursive','autobuild_run:autobuild-2026-09-08','concept-recursive-learning-loop','primary',1.0,'mixed','researcher','The daily loop is research → deliberation → build → test → publication → later revision.','accepted','2026-09-08T20:26:00Z','{"scope":"system_research"}'),
('tag-autobuild-provenance','autobuild_run:autobuild-2026-09-08','concept-provenance-aware-retrieval','supports',1.0,'human','researcher','The run now preserves source signals, rejected candidates, implementation, and human override as distinct records.','accepted','2026-09-08T20:26:00Z','{"scope":"system_research"}');

INSERT OR IGNORE INTO research_object_ctc_tags
(id,object_id,domain_id,tag_role,confidence,tagging_method,actor_type,rationale,status,created_at,provenance_json) VALUES
('tag-autobuild-ctc03','autobuild_run:autobuild-2026-09-08','ctc-domain-03','tests',0.9,'mixed','researcher','The auto-build itself is being studied as a computational tool-to-think-with, not as learner evidence.','accepted','2026-09-08T20:26:00Z','{"scope":"system_research_not_student_evidence"}'),
('tag-autobuild-ctc05','autobuild_run:autobuild-2026-09-08','ctc-domain-05','tests',0.9,'mixed','researcher','The loop requires explicit deliberation, rejection, version judgment, and later human revision.','accepted','2026-09-08T20:26:00Z','{"scope":"system_research_not_student_evidence"}'),
('tag-autobuild-ctc06','autobuild_run:autobuild-2026-09-08','ctc-domain-06','tests',0.85,'mixed','researcher','The process evaluates whether external technical developments fit or conflict with learner agency and critical theory commitments.','accepted','2026-09-08T20:26:00Z','{"scope":"system_research_not_student_evidence"}'),
('tag-autobuild-ctc07','autobuild_run:autobuild-2026-09-08','ctc-domain-07','tests',0.9,'mixed','researcher','The auto-build is deliberately co-authored across machine proposal and human direction rather than treated as autonomous authority.','accepted','2026-09-08T20:26:00Z','{"scope":"system_research_not_student_evidence"}');
